server:
  port: 8091

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
      client:
        registration:
          client-c:
            provider: spring
            client-id: client-c
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: authority-c
        provider:
          spring:
            issuer-uri: http://auth-server:9000

oauth2:
  resource:
    services:
      service-c:
        uri: http://localhost:8092/service-c
