server:
  port: 9001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/uaa/token_keys
      client:
        registration:
          client-c-exchange:
            provider: uaa
            client-id: client-c
            client-secret: secret
            # NOTE:
            # The actual grant_type used for client-c is "urn:ietf:params:oauth:grant-type:jwt-bearer".
            # Temporarily configuring with "client_credentials" in order for the `ClientRegistration` to pass validation,
            # since the "jwt-bearer" grant_type is currently not supported in `AuthorizationGrantType`.
            # Used by `DefaultJwtBearerTokenResponseClient`.
            authorization-grant-type: client_credentials
            scope: authority-c
          client-c:
            provider: uaa
            client-id: client-c
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: authority-c
        provider:
          uaa:
            token-uri: http://localhost:8090/uaa/oauth/token
            jwk-set-uri: http://localhost:8090/uaa/token_keys

oauth2:
  resource:
    services:
      service-c:
        uri: http://localhost:9002/service-c
